// <auto-generated />
using System;
using BandsAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BandsAPI.Migrations
{
    [DbContext(typeof(BandAlbumContext))]
    partial class BandAlbumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BandsAPI.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4d79528-4615-4214-a4b4-c36a232e115a"),
                            BandId = new Guid("88b3c63a-5b77-43cc-b0c0-d1a92fb701a9"),
                            Description = "One of the finest bands it is",
                            Title = "Master of Puppets"
                        },
                        new
                        {
                            Id = new Guid("ebeaed26-91b6-45e7-80bc-ad720d865f40"),
                            BandId = new Guid("68340f77-6e52-4df6-97b8-da14d02e7b5a"),
                            Description = "Destiny plays a role",
                            Title = "Hero of the destiny"
                        },
                        new
                        {
                            Id = new Guid("f9e894ec-ff7a-427e-a75e-a7c19e39027a"),
                            BandId = new Guid("02798642-87b3-481b-a63f-183221f4223b"),
                            Description = "Romantic songs this album has",
                            Title = "King of Romance"
                        },
                        new
                        {
                            Id = new Guid("d5669b26-3415-4682-9c3a-7796b6ce5ca6"),
                            BandId = new Guid("ca4a6a3b-13e0-411c-9f84-28e56b80b99e"),
                            Description = "Harmonic destruction never returns back",
                            Title = "Cites of the harmony"
                        });
                });

            modelBuilder.Entity("BandsAPI.Entities.Band", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("datetime2");

                    b.Property<string>("MainGenre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Bands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88b3c63a-5b77-43cc-b0c0-d1a92fb701a9"),
                            Founded = new DateTime(1980, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Heavy Metal",
                            Name = "Metallica"
                        },
                        new
                        {
                            Id = new Guid("68340f77-6e52-4df6-97b8-da14d02e7b5a"),
                            Founded = new DateTime(1980, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Heavy Metal",
                            Name = "Metallica"
                        },
                        new
                        {
                            Id = new Guid("02798642-87b3-481b-a63f-183221f4223b"),
                            Founded = new DateTime(1980, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Rock",
                            Name = "Abba"
                        },
                        new
                        {
                            Id = new Guid("ca4a6a3b-13e0-411c-9f84-28e56b80b99e"),
                            Founded = new DateTime(1980, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Jazz",
                            Name = "Hellua"
                        });
                });

            modelBuilder.Entity("BandsAPI.Entities.Album", b =>
                {
                    b.HasOne("BandsAPI.Entities.Band", "Band")
                        .WithMany("Albums")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
